[advisories]
version = 2

[bans]
multiple-versions = "deny"

[licenses]
version = 2
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = ["Apache-2.0", "MIT", "BSD-3-Clause", "Zlib", "Unicode-3.0"]
